language: cpp
os: linux
dist: bionic
compiler: g++
env:
  matrix:
    - MPI=openmpi

before_install: 
        - pyenv global 3.8
        - cd py
        - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
        - export MPI_VERSION="3.1"
        - export MPI_FULL_VERSION="3.1.3"
        - source ci/install_mpi.sh
        - echo $MPI_CC
        - echo $MPI_CXX
        - echo $MPI_EXEC
        - env MPICC=$MPI_CC pipenv install --skip-lock
        - pip3 -q install .
script: 
        - cd ..
        - cd tests
        - pytest

