language: cpp
os: linux
dist: bionic
compiler: g++
env:
  matrix:
    - MPI=mpich

before_install: 
        - pyenv global 3.8
        - cd py
        - pip3 -q install .
script: 
        - cd ..
        - cd tests
        - pytest

