language: cpp
os: linux
dist: bionic
compiler: g++
env:
  matrix:
    - MPI=openmpi

before_install: 
        - pyenv global 3.8
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh
        - ./miniconda.sh -b -p $HOME/miniconda
        - export PATH=$HOME/miniconda/bin:$PATH
        - conda update --yes conda
        - conda install --yes mpi4py mpich
        - cd py
        - pip3 -q install .[Travis]
script: 
        - cd ..
        - cd tests
        - pytest

