language: cpp
os: linux
dist: bionic
compiler: g++
env:
  matrix:
    - MPI=openmpi
services:
  - xvfb
before_install: 
        - pyenv global 3.8
        - cd py
        - pip -q install .
        - pip -q install .[Hessian]
script: 
        - cd ..
        - cd tests
        - pytest . --show-capture=no --disable-warnings -q


