language: cpp
os: linux
dist: bionic
compiler: g++
before_install: 
        - pyenv global 3.8
        - cd py
        - pip3 -q install .
script: 
        - cd ..
        - cd tests
        - pytest

