language: cpp
os: linux
dist: bionic
compiler: g++
before_install: 
        - pyenv global 3.8
        - pip install pybind11
        - pip install pytest
        - pip install numpy
script: 
        - cd tests
        - pytest

